const translations = {
    en: {
        nav_home: "Home",
        nav_projects: "Projects",
        nav_resume: "Resume",
        hero_title: "Building <span class='gradient-text-subtle'>Intelligent</span> Systems",
        hero_bio_p1: "I am Rodrigo Donoso Yáñez, an AI/ML developer working at the intersection of data, systems, and decision intelligence. My work focuses on designing machine learning pipelines, feature engineering frameworks, and modular AI architectures that transform complex data into reliable decision systems.",
        hero_bio_p2: "I believe the best solutions emerge when we listen first, then build with purpose, bringing curiosity and clarity to complex architectural challenges.",
        btn_explore: "Explore Projects",
        btn_resume: "View Resume",
        sec_about: "About Me",
        about_p1: "I'm a passionate AI/ML emerging developer. In my short tenure as a newly IBM-ML-AI certified professional I have already been designing and deploying intelligent systems that effectively empower and positively contribute to stakeholders and market communities. My expertise spans the full machine learning lifecycle—from data preprocessing and model development to production deployment and monitoring. I thrive on solving complex problems and turning current trends topics by transforming my own research work into practical applications.",
        core_tech: "Core Tech Stack",
        sec_achievements: "Recent Achievements",
        ach_1_title: "AI Decision Systems Architecture (2026)",
        ach_1_desc: "Completed the impelmentation of an agentic credit risk decision platform integrating machine learning models, dynamic signals, and rule-based governance to produce explainable credit decisions.",
        ach_2_title: "Automated Essay Scoring System (AES)",
        ach_2_desc: "Development of a two-phase NLP pipeline for IELTS writing evaluation, combining semantic feature extraction and fine-tuned language models to analyze coherence, grammar, and lexical richness.",
        ach_3_title: "Technical Publications",
        ach_3_desc: "Published 2 new authored research-style engineering articles on machine learning systems, experimentation frameworks, and AI decision architectures, published on Medium and Weights & Biases.",
        ach_4_title: "Open Source & Engineering Contributions",
        ach_4_desc: "Active contributor to open-source ecosystems including GitHub, Hugging Face, and Kaggle, with projects focused on ML systems, experimentation workflows, and AI infrastructure.",
        sec_publications: "Publications",
        pub_1_title: "Deep Learning Optimization Techniques for NLP Tasks (Oct, 2025)",
        pub_1_desc: "An in-depth analysis of optimization strategies for transformer-based models, exploring adaptive learning rates, gradient clipping, and mixed precision training to enhance performance in natural language processing applications.",
        pub_2_title: "Multi-Task Learning with DeBERTa: A Practical Guide (Oct, 2025)",
        pub_2_desc: "A comprehensive and detailed 'Report' (W&B report-like) on implementing multi-task learning architectures using DeBERTa models, covering fine-tuning strategies, loss balancing, and evaluation metrics for complex NLP scenarios.",
        pub_3_title: "Designing an Agentic Credit Risk Platform (Mar, 2026)",
        pub_3_desc: "A system design article exploring how machine learning models, dynamic signals, and rule-based governance can be integrated into a modular AI decision architecture for credit risk evaluation.",
        pub_3_meta: "Platform: Medium | Focus: AI Systems Architecture, Machine Learning, Decision Systems, Risk Modeling",
        pub_4_title: "Experimentation Framework for Credit Risk Modeling (Mar, 2026)",
        pub_4_desc: "A technical report documenting the experimentation workflow behind risk modeling systems, including feature engineering strategies, synthetic data augmentation, and threshold optimization for decision-oriented machine learning.",
        pub_4_meta: "Platform: Weights & Biases (W&B) | Focus: ML Experimentation, Feature Engineering, Model Evaluation, Risk Analytics",
        pub_link: "Read Article",
        pub_link_report: "Read Report",
        sec_projects: "Featured Projects",
        proj3_desc: "Modular architecture supporting Google Vertex AI and AWS SageMaker for end-to-end machine learning lifecycle management.",
        
        // Detailed Projects
        proj_group_1: "Agentic Credit Risk Platform",
        proj_group_2: "NLP System — IELTS Writing Evaluation",
        
        proj_card_1_title: "Agentic Credit Risk Decision System",
        proj_card_1_desc: "Design of a modular AI decision platform integrating multiple risk models, dynamic signals, and a governance layer for explainable credit approval pipelines.",
        proj_card_2_title: "Credit Risk Modeling with Gradient Boosting",
        proj_card_2_desc: "Development and experimentation of specialized risk models using gradient boosting techniques on structured financial datasets. Focus areas include feature engineering, class imbalance handling, and threshold optimization.",
        proj_card_3_title: "BRMS Decision Governance with Red Hat PAM",
        proj_card_3_desc: "Implementation of a rule-based decision governance layer using enterprise decision management tools. Integrates model predictions with policy rules for transparent decisions.",
        proj_card_4_title: "Dynamic Risk Signal Integration",
        proj_card_4_desc: "Design of contextual signal ingestion components that enrich credit decisions with dynamic indicators such as behavioral signals and external contextual data.",
        proj_card_5_title: "NLP Pipeline for Essay Evaluation",
        proj_card_5_desc: "Development of an NLP system for evaluating English writing responses using semantic feature extraction and structured linguistic signals. Analyzes grammar, coherence, and lexical usage.",
        proj_card_6_title: "Semantic Feature Extraction",
        proj_card_6_desc: "Design of linguistic feature extractors capturing semantic coherence, lexical richness, and structural writing patterns for interpretable ML signals.",
        proj_card_7_title: "Transformer Model Fine-Tuning",
        proj_card_7_desc: "Fine-tuning of transformer-based language models for automated writing evaluation tasks, adapting pretrained models to structured scoring frameworks.",
        
        // Skills Section
        sec_tech_skills: "Technical Skill Set",
        skill_cat_ml: "ML/AI Frameworks",
        skill_cat_lang: "Languages & Tools",
        skill_cat_cloud: "Cloud & MLOps",
        
        // Resume Specifics
        resume_title: "AI & ML Developer",
        btn_download_cv: "Download Resume",
        cv_file: "Curriculum/Curric-AI-ML Develop-RDonoso-2026 (Engl).pdf",
        summary_title: "Professional Summary",
        summary_text: "Junior / Semi-Senior ML & AI Developer focused on building end-to-end, production-minded systems rather than isolated models. Over the last year I have delivered two industry-relevant portfolio projects: an IELTS essay scoring system and a credit-approval decision platform, using Python, Docker and cloud platforms (Vertex AI, AWS SageMaker). I rely heavily on AI coding assistants (GPT, Claude, Gemini) to speed up implementation while I focus on system design, data contracts, evaluation and reliability. I am looking for a role where I can grow as an engineer and contribute to scalable AI solutions in close collaboration with data, platform and product teams.",
        res_exp: "Work Experience",
        date_sep_pres: "Sep 2025 – Present | Remote-Independent",
        role_1: "AI & ML Systems Developer – Independent Project",
        comp_1: "Credit-Approval Decision Platform",
        desc_1: "Planned, designed and developed an end-to-end credit-approval decision system combining multiple ML models into a single auditable decision. Factored notebooks into production-minded training scripts with versioned datasets. Built a policy-decider layer for BRMS integration (Red Hat RHPAM). Containerized the workflow with Docker for GCP/AWS deployment. Defined data contracts for Agentic workflows (LangChain).",
        date_jun_sep: "Jun 2025 – Sep 2025 | Remote",
        role_2: "AI & Machine Learning Developer – Independent Project",
        comp_2: "IELTS Essay Scoring System",
        desc_2: "Designed an automated scoring system using DeBERTa-based architecture predicting multiple traits. Owned full ML pipeline: data cleaning, splits, multi-head modeling, calibration. Migrated to scripted training for APIs. Ran experiments on Vertex AI & AWS SageMaker.",
        date_mar_jun: "Mar 2025 – Jun 2025 | Remote",
        role_3: "Junior ML & AI Engineer – Capstone Projects",
        comp_3: "IBM-Academy Generative AI Engineering",
        desc_3: "Deep Learning for tabular/time-series (PyTorch/Keras). GenAI web app (Flask + Python) with LLM API. RAG patterns & data evaluation workflows. Applied software engineering best practices: Git/GitHub, modular code, docs.",
        date_dec_pres: "Dec 2024 – Present | Remote",
        role_4: "AI Trainer & Prompt Designer – Freelance",
        comp_4: "Outlier / Alignerr",
        desc_4: "Evaluated LLM outputs and provided structured feedback to improve model behavior (RLHF). Developed strong sense of LLM limitations, edge cases, and safety components.",
        
        res_edu: "Education & Certifications",
        date_mar_jun_25: "Mar 2025 – Jun 2025 | Remote",
        edu_1: "Generative AI Engineering Specialization",
        edu_1_comp: "IBM-Academy / Coursera - Professional Certificate",
        edu_2: "AA in Humanities, Arts and Languages",
        edu_2_comp: "San Francisco City College - California, USA",
        edu_3: "Major: Accounting - Auditing (Public Auditor)",
        edu_3_comp: "University of Santiago of Chile (USACH)",
        
        res_comp: "Core Competencies",
        comp_prog: "Programming & ML:",
        comp_prog_desc: "Python (Pandas, NumPy, scikit-learn, PyTorch), Jupyter, basic Flask APIs.",
        comp_cloud: "Cloud & MLOps:",
        comp_cloud_desc: "GCP (Vertex AI), AWS (SageMaker, S3, EC2), Docker, Linux; early IaC.",
        comp_back: "Backend & Data:",
        comp_back_desc: "REST-style services, JSON data contracts, SQL basics, data pipelines mindset.",
        comp_ai: "AI/GenAI:",
        comp_ai_desc: "LLMs, embeddings, prompt engineering, RAG, agentic frameworks (LangChain).",
        comp_prac: "Practices:",
        comp_prac_desc: "Git/GitHub, clean code, tracking, documentation, iterative cycles.",
        
        res_lang: "Languages",
        lang_en: "English:",
        lang_fluent: "Fluent-Advanced",
        lang_es: "Spanish:",
        lang_native: "Native",

        // Metadata
        meta_interests: "Main Interests",
        meta_profile: "Profile Alignment",
        int_strat: "Strategic Communication",
        int_journ: "Journalism & Social Media",
        int_music: "Music",
        int_mkt: "Marketing",
        int_genai: "Generative AI",
        int_ml: "Machine Learning",
        int_feat: "Feature Writing",
        int_lang: "Languages",
        int_res: "Researching",
        int_photo: "Photography",
        int_run: "10K Running",
        prof_team: "TEAM PLAYER",
        prof_vent: "VENTURER",
        prof_hust: "HUSTLER",
        prof_comm: "COMMANDER",
        
        footer_tagline: "Building intelligent solutions for tomorrow",
        footer_connect: "Let's Connect"
    },
    es: {
        nav_home: "Inicio",
        nav_projects: "Proyectos",
        nav_resume: "Currículum",
        hero_title: "Construyendo Sistemas <span class='gradient-text-subtle'>Inteligentes</span>",
        hero_bio_p1: "Soy Rodrigo Donoso Yáñez, un desarrollador de IA/ML que trabaja en la intersección de los datos, los sistemas y la inteligencia de decisiones. Mi trabajo se centra en el diseño de pipelines de machine learning, frameworks de ingeniería de características y arquitecturas modulares de IA que transforman datos complejos en sistemas de decisión confiables.",
        hero_bio_p2: "Creo que las mejores soluciones surgen cuando escuchamos primero y luego construimos con propósito, aportando curiosidad y claridad a desafíos arquitectónicos complejos.",
        btn_explore: "Explorar Proyectos",
        btn_resume: "Ver Currículum",
        sec_about: "Sobre Mí",
        about_p1: "Soy un desarrollador emergente y apasionado por la IA/ML. En mi corta trayectoria como profesional recientemente certificado por IBM-ML-AI, ya he diseñado y desplegado sistemas inteligentes que empoderan y contribuyen positivamente a las comunidades. Mi experiencia abarca todo el ciclo de vida del aprendizaje automático, desde el preprocesamiento de datos hasta el despliegue y monitoreo en producción. Me apasiona resolver problemas complejos y transformar mi propio trabajo de investigación en aplicaciones prácticas.",
        core_tech: "Stack Tecnológico Base",
        sec_achievements: "Logros Recientes",
        ach_1_title: "Arquitectura de Sistemas de Decisión de IA (2026)",
        ach_1_desc: "Implementación completa de una plataforma agéntica de decisión de riesgo crediticio que integra modelos de machine learning, señales dinámicas y gobernanza basada en reglas para producir decisiones crediticias explicables.",
        ach_2_title: "Sistema de Puntuación Automatizada de Ensayos (AES)",
        ach_2_desc: "Desarrollo de un pipeline de NLP en dos fases para la evaluación de escritura del IELTS, combinando extracción de características semánticas y modelos de lenguaje ajustados para analizar coherencia, gramática y riqueza léxica.",
        ach_3_title: "Publicaciones Técnicas",
        ach_3_desc: "Publicación de 2 nuevos artículos de ingeniería de estilo investigativo sobre sistemas de machine learning, frameworks de experimentación y arquitecturas de decisión de IA, publicados en Medium y Weights & Biases.",
        ach_4_title: "Contribuciones de Ingeniería y Código Abierto",
        ach_4_desc: "Contribuidor activo a ecosistemas de código abierto incluyendo GitHub, Hugging Face y Kaggle, con proyectos enfocados en sistemas de ML, flujos de trabajo de experimentación e infraestructura de IA.",
        sec_publications: "Publicaciones",
        pub_1_title: "Técnicas de Optimización de Deep Learning para NLP (Oct, 2025)",
        pub_1_desc: "Un análisis profundo de estrategias de optimización para modelos basados en transformers, explorando tasas de aprendizaje adaptativas, recorte de gradientes y entrenamiento de precisión mixta.",
        pub_2_title: "Aprendizaje Multitarea con DeBERTa: Guía Práctica (Oct, 2025)",
        pub_2_desc: "Un 'Reporte' exhaustivo y detallado sobre la implementación de arquitecturas de aprendizaje multitarea usando modelos DeBERTa, cubriendo estrategias de fine-tuning y balanceo de pérdidas.",
        pub_3_title: "Diseño de una Plataforma Agéntica de Riesgo Crediticio (Mar, 2026)",
        pub_3_desc: "Un artículo de diseño de sistemas que explora cómo los modelos de machine learning, las señales dinámicas y la gobernanza basada en reglas pueden integrarse en una arquitectura modular de decisión de IA para la evaluación del riesgo crediticio.",
        pub_3_meta: "Plataforma: Medium | Foco: Arquitectura de Sistemas de IA, Machine Learning, Sistemas de Decisión, Modelado de Riesgos",
        pub_4_title: "Framework de Experimentación para el Modelado de Riesgo Crediticio (Mar, 2026)",
        pub_4_desc: "Un informe técnico que documenta el flujo de trabajo de experimentación detrás de los sistemas de modelado de riesgos, incluyendo estrategias de ingeniería de características, aumento de datos sintéticos y optimización de umbrales para machine learning orientado a decisiones.",
        pub_4_meta: "Plataforma: Weights & Biases (W&B) | Foco: Experimentación de ML, Ingeniería de Características, Evaluación de Modelos, Analítica de Riesgos",
        pub_link: "Leer Artículo",
        pub_link_report: "Leer Reporte",
        sec_projects: "Proyectos Destacados",
        proj3_desc: "Arquitectura modular que soporta Google Vertex AI y AWS SageMaker para la gestión del ciclo de vida del aprendizaje automático de extremo a extremo.",

        // Detailed Projects
        proj_group_1: "Plataforma de Riesgo Crediticio Agéntica",
        proj_group_2: "Sistema NLP — Evaluación de Escritura IELTS",

        proj_card_1_title: "Sistema Agéntico de Decisión de Riesgo Crediticio",
        proj_card_1_desc: "Diseño de una plataforma modular de decisión de IA que integra múltiples modelos de riesgo, señales dinámicas y una capa de gobernanza para pipelines de aprobación de crédito explicables.",
        proj_card_2_title: "Modelado de Riesgo con Gradient Boosting",
        proj_card_2_desc: "Desarrollo y experimentación de modelos de riesgo especializados utilizando técnicas de gradient boosting en conjuntos de datos financieros estructurados. Enfoque en ingeniería de características y optimización de umbrales.",
        proj_card_3_title: "Gobernanza de Decisiones BRMS con Red Hat PAM",
        proj_card_3_desc: "Implementación de una capa de gobernanza de decisiones basada en reglas. Integra predicciones de modelos con reglas de políticas para decisiones transparentes y auditables.",
        proj_card_4_title: "Integración de Señales de Riesgo Dinámicas",
        proj_card_4_desc: "Diseño de componentes de ingesta de señales contextuales que enriquecen las decisiones crediticias con indicadores dinámicos y datos contextuales externos.",
        proj_card_5_title: "Pipeline de NLP para Evaluación de Ensayos",
        proj_card_5_desc: "Desarrollo de un sistema de NLP para evaluar respuestas escritas en inglés mediante extracción de características semánticas y señales lingüísticas estructuradas.",
        proj_card_6_title: "Extracción de Características Semánticas",
        proj_card_6_desc: "Diseño de extractores de características lingüísticas que capturan la coherencia semántica y la riqueza léxica para señales de ML interpretables.",
        proj_card_7_title: "Fine-Tuning de Modelos Transformer",
        proj_card_7_desc: "Ajuste fino de modelos de lenguaje basados en transformers para tareas de evaluación de escritura automatizada, adaptando modelos pre-entrenados a marcos de puntuación estructurados.",
        
        // Skills Section
        sec_tech_skills: "Set de Habilidades Técnicas",
        skill_cat_ml: "Frameworks de ML/IA",
        skill_cat_lang: "Lenguajes y Herramientas",
        skill_cat_cloud: "Nube y MLOps",
        
        // Resume Specifics
        resume_title: "Desarrollador de IA y ML",
        btn_download_cv: "Descargar CV",
        cv_file: "Curriculum/Curric-AI-ML Develop-RDonoso-2026 (Esp).pdf",
        summary_title: "Resumen Profesional",
        summary_text: "Desarrollador Junior / Semi-Senior de ML e IA enfocado en la construcción de sistemas de extremo a extremo y orientados a la producción en lugar de modelos aislados. Durante el último año he entregado dos proyectos de portafolio relevantes para la industria: un sistema de puntuación de ensayos IELTS y una plataforma de decisión de aprobación de crédito, utilizando Python, Docker y plataformas en la nube (Vertex AI, AWS SageMaker). Me apoyo fuertemente en asistentes de código de IA (GPT, Claude, Gemini) para acelerar la implementación mientras me enfoco en el diseño de sistemas, contratos de datos, evaluación y confiabilidad. Busco un rol en el que pueda crecer como ingeniero y contribuir a soluciones de IA escalables en estrecha colaboración con equipos de datos, plataformas y productos.",
        res_exp: "Experiencia Laboral",
        date_sep_pres: "Sep 2025 – Presente | Remoto-Independiente",
        role_1: "Desarrollador de Sistemas IA y ML – Proyecto Independiente",
        comp_1: "Plataforma de Decisión de Aprobación de Crédito",
        desc_1: "Planifiqué, diseñé y desarrollé un sistema integral de decisión de aprobación de crédito combinando múltiples modelos ML en una sola decisión auditable. Factoricé notebooks en scripts de entrenamiento orientados a producción con datasets versionados. Construí una capa de políticas para integración con BRMS (Red Hat RHPAM). Contenericé el flujo con Docker para GCP/AWS. Definí contratos de datos para flujos de LangChain.",
        date_jun_sep: "Jun 2025 – Sep 2025 | Remoto",
        role_2: "Desarrollador de IA y Machine Learning – Proyecto Independiente",
        comp_2: "Sistema de Puntuación de Ensayos IELTS",
        desc_2: "Diseñé un sistema de puntuación automatizado usando arquitectura basada en DeBERTa prediciendo múltiples rasgos. Administré todo el pipeline ML: limpieza, particiones, modelo multi-cabeza, calibración. Migré a scripts fijos para APIs. Ejecuté experimentos en Vertex AI & AWS SageMaker.",
        date_mar_jun: "Mar 2025 – Jun 2025 | Remoto",
        role_3: "Ingeniero Junior IA y ML – Proyectos Finales",
        comp_3: "Ingeniería en IA Generativa IBM-Academy",
        desc_3: "Deep Learning para datos tabulares/series temporales (PyTorch/Keras). Web app GenAI (Flask + Python) con API LLM. Patrones RAG & evaluación de datos. Apliqué mejores prácticas: Git/GitHub, código modular, docs.",
        date_dec_pres: "Dic 2024 – Presente | Remoto",
        role_4: "Entrenador de IA & Diseñador de Prompts – Freelance",
        comp_4: "Outlier / Alignerr",
        desc_4: "Evalué salidas LLM y proporcioné retroalimentación estructurada para mejorar el comportamiento (RLHF). Desarrollé alto sentido de límites de LLMs, casos atípicos y seguridad.",
        
        res_edu: "Educación y Certificaciones",
        date_mar_jun_25: "Mar 2025 – Jun 2025 | Remoto",
        edu_1: "Especialización en Ingeniería de IA Generativa",
        edu_1_comp: "IBM-Academy / Coursera - Certificado Profesional",
        edu_2: "AA en Humanidades, Artes e Idiomas",
        edu_2_comp: "City College de San Francisco - California, EE. UU.",
        edu_3: "Especialidad: Contabilidad - Auditoría (Auditor Público)",
        edu_3_comp: "Universidad de Santiago de Chile (USACH)",
        
        res_comp: "Competencias Básicas",
        comp_prog: "Programación y ML:",
        comp_prog_desc: "Python (Pandas, NumPy, scikit-learn, PyTorch), Jupyter, APIs básicas de Flask.",
        comp_cloud: "Nube y MLOps:",
        comp_cloud_desc: "GCP (Vertex AI), AWS (SageMaker, S3, EC2), Docker, Linux; bases IaC.",
        comp_back: "Backend y Datos:",
        comp_back_desc: "Servicios REST, contratos de datos JSON, bases SQL, mentalidad de pipelines.",
        comp_ai: "IA/GenAI:",
        comp_ai_desc: "LLMs, embeddings, prompts, RAG, frameworks para agentes (LangChain).",
        comp_prac: "Prácticas:",
        comp_prac_desc: "Git/GitHub, código limpio, rastreo, documentación, ciclos de sprints.",
        
        res_lang: "Idiomas",
        lang_en: "Inglés:",
        lang_fluent: "Fluido-Avanzado",
        lang_es: "Español:",
        lang_native: "Nativo",

        // Metadata
        meta_interests: "Intereses Principales",
        meta_profile: "Alineación de Perfil",
        int_strat: "Comunicación Estratégica",
        int_journ: "Periodismo y Redes Sociales",
        int_music: "Música",
        int_mkt: "Marketing",
        int_genai: "IA Generativa",
        int_ml: "Machine Learning",
        int_feat: "Escritura de Reportajes",
        int_lang: "Idiomas",
        int_res: "Investigación",
        int_photo: "Fotografía",
        int_run: "Carreras 10K",
        prof_team: "JUGADOR DE EQUIPO",
        prof_vent: "EMPRENDEDOR",
        prof_hust: "ESFORZADO",
        prof_comm: "COMANDANTE",
        
        footer_tagline: "Construyendo soluciones inteligentes para el mañana",
        footer_connect: "¡Conectemos!"
    }
};

window.i18n = translations;
